### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Pinkeltje** [stefanschulz/cuterweblinks#2]
Module not working on Joomla 4.3.4 tested also with default Cassiopeia template.
Error: `Return value of TheLoom\Module\CuterWeblinks\Site\Helper\CuterWeblinksHelper::getLinks() must be an instance of TheLoom\Module\CuterWeblinks\Site\Helper\mixed, array returned `

**Comment by stefanschulz** [comment]
Hi @Pinkeltje,

This is strange, as I am running the module on Joomla 4.3.4 as well.
Could you provide information on which version of the module you are running? 
Also, on which PHP version Joomla is running?

Thank you,
Stefan

**Comment by Pinkeltje** [comment]
Already solved. It was a problem with weblinks component after migration.  Thx.

**Comment by stefanschulz** [comment]
Great it resolved quickly. Have fun with cuter weblinks :)
